
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import java.awt.CardLayout;
import java.awt.HeadlessException;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User
 */
public class mgusers extends javax.swing.JFrame {

    private static final String filepath = "src\\netnexus.json";
    private static final JSONParser jsonParser = new JSONParser();
    private static JSONObject record = new JSONObject();
    private static JSONArray users = new JSONArray();

    public mgusers() {
        initComponents();

        setupRowSelectionListener();
        try {
            filecheck(); // Load data from JSON file
        } catch (IOException | ParseException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private TableRowSorter<DefaultTableModel> rowSorter;

    private void setupTableFilter() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (rowSorter == null) {
            rowSorter = new TableRowSorter<>(model);
            jTable1.setRowSorter(rowSorter);
        }

        srchTF.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filterTable();
            }
        });
    }

    private void filterTable() {
        String searchText = srchTF.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);

        if (searchText.isEmpty()) {
            sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
                @Override
                public boolean include(Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                    String username = (String) entry.getValue(0);
                    return !"admin".equalsIgnoreCase(username); // Exclude admin
                }
            });
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddBttn = new javax.swing.JButton();
        EdtBttn = new javax.swing.JButton();
        DltBttn = new javax.swing.JButton();
        backbtn1 = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        srchTF = new javax.swing.JTextField();
        editpnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EdtUsnTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EdtNewUsnTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EdtBlncTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EdtCb = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        EdtPssTF = new javax.swing.JTextField();
        NewLogDtTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        SveBttn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        newEdittimeTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        addpnl = new javax.swing.JPanel();
        AddUsnTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddPssTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AddBlncTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AddLoginDteTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vipcmb = new javax.swing.JComboBox<>();
        addbtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        addtimeTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddBttn.setText("Add User");
        AddBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBttnActionPerformed(evt);
            }
        });
        jPanel1.add(AddBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, -1));

        EdtBttn.setText("Edit User");
        EdtBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtBttnActionPerformed(evt);
            }
        });
        jPanel1.add(EdtBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 100, -1));

        DltBttn.setText("Delete User");
        DltBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DltBttnActionPerformed(evt);
            }
        });
        jPanel1.add(DltBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 100, -1));

        backbtn1.setText("Back");
        backbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 14, 57, 17));

        userBtn.setText("Users");
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        jPanel1.add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, -1));

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Time", "Balance", "Login Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 830, 320));

        srchTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srchTFKeyReleased(evt);
            }
        });
        jPanel3.add(srchTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 350, -1));

        jPanel2.add(jPanel3, "card6");

        editpnl.setMinimumSize(new java.awt.Dimension(925, 500));
        editpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Edit User");
        editpnl.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel8.setText("Search Username:");
        editpnl.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, 20));

        EdtUsnTF.setText("Type Username");
        EdtUsnTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdtUsnTFMouseClicked(evt);
            }
        });
        EdtUsnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtUsnTFActionPerformed(evt);
            }
        });
        editpnl.add(EdtUsnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 165, -1));

        jLabel9.setText("Edit Username:");
        editpnl.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 95, -1));

        EdtNewUsnTF.setText("Enter New Username");
        EdtNewUsnTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdtNewUsnTFMouseClicked(evt);
            }
        });
        EdtNewUsnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtNewUsnTFActionPerformed(evt);
            }
        });
        editpnl.add(EdtNewUsnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 165, -1));

        jLabel10.setText("Balance:");
        editpnl.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 99, -1));

        EdtBlncTF.setText("0.0");
        EdtBlncTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdtBlncTFMouseClicked(evt);
            }
        });
        EdtBlncTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtBlncTFActionPerformed(evt);
            }
        });
        editpnl.add(EdtBlncTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 165, -1));

        jLabel11.setText("VIP Status:");
        editpnl.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        EdtCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bronze", "Silver", "Gold" }));
        editpnl.add(EdtCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jLabel16.setText("New Password:");
        editpnl.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        EdtPssTF.setText("Type Password");
        EdtPssTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdtPssTFMouseClicked(evt);
            }
        });
        EdtPssTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtPssTFActionPerformed(evt);
            }
        });
        editpnl.add(EdtPssTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 160, -1));

        NewLogDtTF.setText("mm-dd-yyyy");
        NewLogDtTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewLogDtTFMouseClicked(evt);
            }
        });
        NewLogDtTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewLogDtTFActionPerformed(evt);
            }
        });
        editpnl.add(NewLogDtTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 160, -1));

        jLabel17.setText("New Login Date:");
        editpnl.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 106, -1));

        SveBttn.setText("Save ");
        SveBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SveBttnActionPerformed(evt);
            }
        });
        editpnl.add(SveBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLabel19.setText("New Time Session:");
        editpnl.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        newEdittimeTF.setText("00:00:00");
        newEdittimeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEdittimeTFActionPerformed(evt);
            }
        });
        newEdittimeTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newEdittimeTFKeyReleased(evt);
            }
        });
        editpnl.add(newEdittimeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 160, -1));

        jLabel21.setText("Logins:");
        editpnl.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jTextField2.setText("0");
        editpnl.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jPanel2.add(editpnl, "card2");
        editpnl.getAccessibleContext().setAccessibleDescription("");

        AddUsnTF.setText("Enter Username");
        AddUsnTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUsnTFMouseClicked(evt);
            }
        });
        AddUsnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUsnTFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Add User");

        jLabel2.setText("Username");

        jLabel3.setText("Password:");

        AddPssTF.setText("Enter Password");
        AddPssTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddPssTFMouseClicked(evt);
            }
        });

        jLabel4.setText("Balance:");

        AddBlncTF.setText("0.0");
        AddBlncTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBlncTFMouseClicked(evt);
            }
        });
        AddBlncTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBlncTFActionPerformed(evt);
            }
        });
        AddBlncTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AddBlncTFKeyReleased(evt);
            }
        });

        jLabel5.setText("Login Date:");

        AddLoginDteTF.setText("mm-dd-yyyy");
        AddLoginDteTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLoginDteTFMouseClicked(evt);
            }
        });

        jLabel6.setText("VIP Status:");

        vipcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bronze", "Silver", "Gold" }));

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        jLabel18.setText("Time Session:");

        addtimeTF.setText("00:00:00");
        addtimeTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtimeTFMouseClicked(evt);
            }
        });
        addtimeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtimeTFActionPerformed(evt);
            }
        });

        jLabel20.setText("Logins:");

        jTextField1.setText("0");

        javax.swing.GroupLayout addpnlLayout = new javax.swing.GroupLayout(addpnl);
        addpnl.setLayout(addpnlLayout);
        addpnlLayout.setHorizontalGroup(
            addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpnlLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpnlLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(addpnlLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4)
                    .addGroup(addpnlLayout.createSequentialGroup()
                        .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AddUsnTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddBlncTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addpnlLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(43, 43, 43)
                                .addComponent(jTextField1))
                            .addGroup(addpnlLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vipcmb, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addpnlLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(AddPssTF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddLoginDteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addpnlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addbtn)
                                    .addComponent(jLabel18))
                                .addGap(9, 9, 9)
                                .addComponent(addtimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(58, 58, 58))
        );
        addpnlLayout.setVerticalGroup(
            addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpnlLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddUsnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPssTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBlncTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddLoginDteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addComponent(jLabel18)
                    .addComponent(addtimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vipcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(addbtn)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel2.add(addpnl, "card1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBttnActionPerformed
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card1");
    }//GEN-LAST:event_AddBttnActionPerformed

    private void EdtUsnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtUsnTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtUsnTFActionPerformed
    // TODO add your handling code here:

    private void EdtNewUsnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtNewUsnTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtNewUsnTFActionPerformed

    private void EdtBlncTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtBlncTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtBlncTFActionPerformed

    private void AddUsnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUsnTFActionPerformed
        AddUsnTF.setText("");
    }//GEN-LAST:event_AddUsnTFActionPerformed

    private void EdtBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtBttnActionPerformed

        // Get the selected row from the JTable
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            // If no row is selected, show a warning message
            JOptionPane.showMessageDialog(this, "Please select a user to edit.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Retrieve data from the selected row
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String username = (String) model.getValueAt(selectedRow, 0);
        String userTime = (String) model.getValueAt(selectedRow, 1);
        String balance = String.valueOf(model.getValueAt(selectedRow, 2));
        String lastLogin = (String) model.getValueAt(selectedRow, 3);

        // Populate the edit panel fields with the selected row's data
        EdtUsnTF.setText(username);        // Username
        newEdittimeTF.setText(userTime);   // User Time
        EdtBlncTF.setText(balance);        // Balance
        NewLogDtTF.setText(lastLogin);     // Last Login Date

        // Switch to the edit panel
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card2"); // Assuming "card2" is the edit panel

    }//GEN-LAST:event_EdtBttnActionPerformed

    private void DltBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DltBttnActionPerformed
        try {
            removeUsersInactiveFor30Days();
        } catch (IOException | ParseException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Inactive users removed successfully.");
        try {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "No user selected for deletion.");
                return;
            }

            String usernameToDelete = (String) jTable1.getValueAt(selectedRow, 0);
            for (int i = 0; i < users.size(); i++) {
                JSONObject user = (JSONObject) users.get(i);
                if (user.get("username").equals(usernameToDelete)) {
                    users.remove(i);
                    break;
                }
            }

            record.put("users", users);
            save();

            // Remove table row
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(null, "User deleted successfully!");
        } catch (HeadlessException | IOException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_DltBttnActionPerformed

    private void EdtPssTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtPssTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtPssTFActionPerformed
    // TODO add your handling code here:

    private void NewLogDtTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewLogDtTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewLogDtTFActionPerformed

    private void backbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn1ActionPerformed

    }//GEN-LAST:event_backbtn1ActionPerformed

    private void SrchClrBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrchClrBttnActionPerformed

    }//GEN-LAST:event_SrchClrBttnActionPerformed

    private void UserDltBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserDltBttnActionPerformed


    }//GEN-LAST:event_UserDltBttnActionPerformed

    private void SveBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SveBttnActionPerformed

        try {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "No user selected for editing.");
                return;
            }

            String currentUsername = (String) jTable1.getValueAt(selectedRow, 0);
            String newUsername = EdtNewUsnTF.getText().trim();
            String newPassword = EdtPssTF.getText().trim();
            String newBalanceStr = EdtBlncTF.getText().trim();
            double newBalance = Double.parseDouble(newBalanceStr);
            String newVip = (String) EdtCb.getSelectedItem();

            for (Object obj : users) {
                JSONObject user = (JSONObject) obj;
                if (user.get("username").equals(currentUsername)) {
                    user.put("username", newUsername);
                    user.put("password", newPassword);
                    user.put("amount", newBalanceStr);
                    user.put("VipStatus", newVip);
                    user.put("userTime", calculateUserTime(newBalance));
                    break;
                }
            }
            save();

            // Update table row
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setValueAt(newUsername, selectedRow, 0);
            model.setValueAt(newBalanceStr, selectedRow, 2);
            model.setValueAt(newVip, selectedRow, 3);
            JOptionPane.showMessageDialog(null, "User updated successfully!");
        } catch (HeadlessException | IOException | NumberFormatException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_SveBttnActionPerformed

    private void EdtClrBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtClrBttnActionPerformed

    }//GEN-LAST:event_EdtClrBttnActionPerformed

    private void EdtCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtCbActionPerformed


    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

        try {
            String username = AddUsnTF.getText().trim();
            String password = AddPssTF.getText().trim();
            String balanceStr = AddBlncTF.getText().trim();
            double balance = Double.parseDouble(balanceStr);
            String vipStatus = vipcmb.getSelectedItem().toString();
            String loginDate = getCurrentDateTime();

            // Check if user already exists
            for (Object obj : users) {
                JSONObject user = (JSONObject) obj;
                if (user.get("username").equals(username)) {
                    JOptionPane.showMessageDialog(null, "Username already exists!");
                    return;
                }
            }

            String userTime = calculateUserTime(balance);
            JSONObject newUser = new JSONObject();
            newUser.put("username", username);
            newUser.put("password", password);
            newUser.put("amount", balanceStr);
            newUser.put("userTime", userTime);
            newUser.put("lastLogin", loginDate);
            newUser.put("VipStatus", vipStatus);

            users.add(newUser);
            record.put("users", users);
            save();

            // Add the new user to the table
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{username, userTime, balanceStr, loginDate});
            JOptionPane.showMessageDialog(null, "User added successfully!");
        } catch (HeadlessException | IOException | NumberFormatException ex) {
            Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void DltClrBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DltClrBttnActionPerformed

    }//GEN-LAST:event_DltClrBttnActionPerformed

    private void clrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbtnActionPerformed

    }//GEN-LAST:event_clrbtnActionPerformed

    private void AddBlncTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBlncTFActionPerformed

    }//GEN-LAST:event_AddBlncTFActionPerformed

    private void AddUsnTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUsnTFMouseClicked
        AddUsnTF.setText("");
    }//GEN-LAST:event_AddUsnTFMouseClicked

    private void AddPssTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPssTFMouseClicked
        AddPssTF.setText("");    }//GEN-LAST:event_AddPssTFMouseClicked

    private void addtimeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtimeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtimeTFActionPerformed

    private void AddBlncTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBlncTFMouseClicked
        AddBlncTF.setText("");
    }//GEN-LAST:event_AddBlncTFMouseClicked

    private void AddLoginDteTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLoginDteTFMouseClicked
        AddLoginDteTF.setText("");
    }//GEN-LAST:event_AddLoginDteTFMouseClicked

    private void addtimeTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtimeTFMouseClicked
        addtimeTF.setText("");
    }//GEN-LAST:event_addtimeTFMouseClicked

    private void EdtUsnTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdtUsnTFMouseClicked
        EdtUsnTF.setText("");
    }//GEN-LAST:event_EdtUsnTFMouseClicked

    private void EdtNewUsnTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdtNewUsnTFMouseClicked
        EdtNewUsnTF.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_EdtNewUsnTFMouseClicked

    private void EdtBlncTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdtBlncTFMouseClicked
        EdtBlncTF.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_EdtBlncTFMouseClicked

    private void EdtPssTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdtPssTFMouseClicked
        EdtPssTF.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_EdtPssTFMouseClicked

    private void NewLogDtTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewLogDtTFMouseClicked
        NewLogDtTF.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_NewLogDtTFMouseClicked

    private void AddBlncTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddBlncTFKeyReleased
        AddBlncTF.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    String balanceStr = AddBlncTF.getText().trim();
                    if (!balanceStr.isEmpty()) {
                        double balance = Double.parseDouble(balanceStr);
                        String calculatedTime = calculateUserTime(balance);
                        addtimeTF.setText(calculatedTime); // Set the calculated session time
                    } else {
                        addtimeTF.setText("00:00:00"); // Reset if balance is empty
                    }
                } catch (NumberFormatException e) {
                    addtimeTF.setText("00:00:00"); // Reset if invalid input
                }
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_AddBlncTFKeyReleased

    private void newEdittimeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEdittimeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEdittimeTFActionPerformed

    private void newEdittimeTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newEdittimeTFKeyReleased
        EdtBlncTF.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    String balanceStr = EdtBlncTF.getText().trim();
                    if (!balanceStr.isEmpty()) {
                        double balance = Double.parseDouble(balanceStr);
                        String calculatedTime = calculateUserTime(balance);
                        newEdittimeTF.setText(calculatedTime); // Set the calculated session time
                    } else {
                        newEdittimeTF.setText("00:00:00"); // Reset if balance is empty
                    }
                } catch (NumberFormatException e) {
                    newEdittimeTF.setText("00:00:00"); // Reset if invalid input
                }
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_newEdittimeTFKeyReleased

    private void srchTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchTFKeyReleased
        setupTableFilter();        // TODO add your handling code here:
    }//GEN-LAST:event_srchTFKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        setupRowClickListener();        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "card6");        // TODO add your handling code here:
    }//GEN-LAST:event_userBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mgusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mgusers().setVisible(true);
        });
    }

    public void filecheck() throws FileNotFoundException, IOException, ParseException {
        FileReader reader = new FileReader(filepath);

        if (reader.ready()) {
            Scanner scan = new Scanner(reader);
            String line = "";
            while (scan.hasNext()) {
                line = line + scan.nextLine();
            }

            reader.close();

            if (!line.equals("")) {
                reader.close();
                try (FileReader reader2 = new FileReader(filepath)) {
                    record = (JSONObject) jsonParser.parse(reader2);
                    users = (JSONArray) record.get("users");
                    loadTableData(); // Load data into the table
                }
            }
        }
    }

    public static void save() throws IOException {
        try (FileWriter file = new FileWriter(filepath)) {
            file.write(record.toJSONString());
        }
    }

    private String getCurrentDateTime() {
        java.time.LocalDateTime now = java.time.LocalDateTime.now();
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        return now.format(formatter);
    }

    private String calculateUserTime(double balance) {
        int timeInSeconds = (int) ((balance / 20) * 3600); // 1 hour per 20 balance
        int hours = timeInSeconds / 3600;
        int minutes = (timeInSeconds % 3600) / 60;
        int seconds = timeInSeconds % 60;
        return String.format("%02d:%02d:%02d", hours, minutes, seconds);
    }

    private void loadTableData() {
        // Get the DefaultTableModel of the table
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        // Populate table rows with user data from the JSON array
        for (Object obj : users) {
            JSONObject user = (JSONObject) obj;

            // Skip the admin user
            if ("admin".equalsIgnoreCase((String) user.get("username"))) {
                continue;
            }

            model.addRow(new Object[]{
                user.get("username"),
                user.get("userTime"),
                user.get("amount"),
                user.get("lastLogin")
            });
        }
    }

    private void setupRowSelectionListener() {
        jTable1.getSelectionModel().addListSelectionListener(event -> {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) {
                // Populate fields with the selected row's data
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                EdtUsnTF.setText((String) model.getValueAt(selectedRow, 0));
                newEdittimeTF.setText((String) model.getValueAt(selectedRow, 1));
                EdtBlncTF.setText(String.valueOf(model.getValueAt(selectedRow, 2)));
                NewLogDtTF.setText((String) model.getValueAt(selectedRow, 3));
            }
        });
    }

    private void setupRowClickListener() {
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 1) { // Single click
                    int selectedRow = jTable1.getSelectedRow();
                    if (selectedRow != -1) {
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        String username = (String) model.getValueAt(selectedRow, 0);

                        // Search for the user in the JSON array for additional details
                        JSONObject userDetails = null;
                        for (Object obj : users) {
                            JSONObject user = (JSONObject) obj;
                            if (user.get("username").equals(username)) {
                                userDetails = user;
                                break;
                            }
                        }

                        if (userDetails != null) {
                            // Display the user details in a dialog
                            String userInfo = "Username: " + userDetails.get("username")
                                    + "\nPassword: " + userDetails.get("password")
                                    + "\nBalance: " + userDetails.get("amount")
                                    + "\nUser Time: " + userDetails.get("userTime")
                                    + "\nLast Login: " + userDetails.get("lastLogin")
                                    + "\nVIP Status: " + userDetails.get("VipStatus")
                                    + "\nLogins: " + userDetails.get("logins");
                            JOptionPane.showMessageDialog(null, userInfo, "User Details", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
            }
        });
    }

    private void removeUsersInactiveFor30Days() throws FileNotFoundException, IOException, ParseException {
        
            File file = new File(filepath);
            if (!file.exists()) {
                System.err.println("JSON file not found. Skipping removal process.");
                return;
            }

            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(new FileReader(file));
            JSONArray userss = (JSONArray) jsonObject.get("users");

            long currentTime = System.currentTimeMillis();
            long thirtyDaysInMillis = 30L * 24 * 60 * 60 * 1000;
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            boolean[] updated = {false};
            userss.removeIf((Object obj) -> {
                JSONObject user = (JSONObject) obj;
                String lastLoginDateStr = (String) user.get("lastLogin");
                if (lastLoginDateStr == null) {
                    return false;
                }
                try {
                    Date lastLoginDate = dateFormat.parse(lastLoginDateStr);
                    long lastLoginTime = lastLoginDate.getTime();
                    if ((currentTime - lastLoginTime) >= thirtyDaysInMillis) {
                        updated[0] = true;
                        return true;
                    }
                } catch (java.text.ParseException e) {
                    System.err.println("Invalid date format for lastLogin: " + lastLoginDateStr);
                }
                return false;
            });
            if (updated[0]) {
                try (FileWriter writer = new FileWriter(file)) {
                    writer.write(jsonObject.toJSONString());
                } catch (IOException ex) {
                    Logger.getLogger(mgusers.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Removed users inactive for 30 days or more successfully.");
            } else {
                System.out.println("No users found inactive for 30 days or more.");
            }
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddBlncTF;
    private javax.swing.JButton AddBttn;
    private javax.swing.JTextField AddLoginDteTF;
    private javax.swing.JTextField AddPssTF;
    private javax.swing.JTextField AddUsnTF;
    private javax.swing.JButton DltBttn;
    private javax.swing.JTextField EdtBlncTF;
    private javax.swing.JButton EdtBttn;
    private javax.swing.JComboBox<String> EdtCb;
    private javax.swing.JTextField EdtNewUsnTF;
    private javax.swing.JTextField EdtPssTF;
    private javax.swing.JTextField EdtUsnTF;
    private javax.swing.JTextField NewLogDtTF;
    private javax.swing.JButton SveBttn;
    private javax.swing.JButton addbtn;
    private javax.swing.JPanel addpnl;
    private javax.swing.JTextField addtimeTF;
    private javax.swing.JButton backbtn1;
    private javax.swing.JPanel editpnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField newEdittimeTF;
    private javax.swing.JTextField srchTF;
    private javax.swing.JButton userBtn;
    private javax.swing.JComboBox<String> vipcmb;
    // End of variables declaration//GEN-END:variables
}
